name: Generar diagramas PlantUML

on:
  push:
    paths:
      - 'docs/*.puml'
  workflow_dispatch:  # Permite ejecución manual desde GitHub

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Java y Graphviz
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jre graphviz curl

      - name: Descargar PlantUML (última versión)
        run: |
          curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar

      - name: Crear carpeta de salida
        run: mkdir -p output

      - name: Generar imagen desde PlantUML
        run: java -jar plantuml.jar -tpng docs/sistema.puml -o ../output

      - name: Subir imagen como artefacto del pipeline
        uses: actions/upload-artifact@v4
        with:
          name: diagrama-generado
          path: output/sistema.png
